eligible_index = ""
eligible_path = ["", "", "", "", "", "", "", "", "", "", "", ""]
eligible_root = ""
message = ["", "", "", "", "", "", "", ""]
stealth_tweak = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
wallet_secret = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
